---
apiVersion: v1
kind: Service
metadata: 
  name: tss-services
spec:
  selector:
    app: tsses
  ports:
    - name: http
      protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      #Port to forward to inside the pod
      targetPort: 8000
      #Port accessible outside cluster
      nodePort:  30006
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tsse
spec:
  revisionHistoryLimit: 5
  minReadySeconds: 10
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tsses
  template:
    metadata:
      labels:
        app: tsses
    spec:
      containers: 
        - name: tsses
          image: tsses:v3
          ports:
            - containerPort: 8000
